const $=x=>document.getElementById(x);let chart=LightweightCharts.createChart($("tvchart"),{layout:{background:{color:"#0d1222"},textColor:"#aab4d1"},grid:{vertLines:{color:"#1b2338"},horzLines:{color:"#1b2338"}},timeScale:{borderColor:"#2b3550"},rightPriceScale:{borderColor:"#2b3550"}});let cs=chart.addCandlestickSeries({upColor:"#39d39f",downColor:"#ff5d76",wickUpColor:"#39d39f",wickDownColor:"#ff5d76",borderVisible:false});let lastKey="",first=true,count=20;
function f(x){return x==null?"—":Number(x).toFixed(5)}
async function load(){try{const u=`/api/market?symbol=${encodeURIComponent($("pair").value)}&interval=${$("tf").value}`,r=await fetch(u,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);cs.setData(d.bars.map(x=>({time:Math.floor(new Date(x.datetime).getTime()/1000),open:x.open,high:x.high,low:x.low,close:x.close})));chart.timeScale().fitContent();const a=d.analysis;$("sig").textContent=a.eligible?a.signal:"FILTERED";$("conf").textContent=a.confidence+"%";$("entry").textContent=f(a.entry);$("sl").textContent=f(a.sl);$("tp").textContent=f(a.tp);$("why").textContent=a.eligible?a.reasons.join(" · "):"Score di bawah ambang 50%, sinyal tidak diprioritaskan."; $("zones").innerHTML=`S: ${(a.support||[]).map(x=>f(x.price)).join(", ")}<br>R: ${(a.resistance||[]).map(x=>f(x.price)).join(", ")}`;$("smc").innerHTML=`BOS↑ ${a.bosBull?"YA":"tidak"} · BOS↓ ${a.bosBear?"YA":"tidak"}<br>Liquidity sweep: ${a.sweepLow||a.sweepHigh?"YA":"tidak"}`;$("ai").textContent=d.gemini?.text||"Gemini belum aktif";$("live").textContent="● live · "+new Date().toLocaleTimeString("id-ID");const key=`${d.symbol}|${d.interval}|${a.signal}|${a.timestamp}`;if(!first&&key!==lastKey&&a.eligible)pushSignal(d,a);lastKey=key;first=false}catch(e){$("live").textContent="● error: "+e.message}}
async function pushSignal(d,a){if("Notification"in window&&Notification.permission==="granted")new Notification("QwinAi Trade",{body:`${d.symbol} ${a.signal} ${a.confidence}% | Entry ${f(a.entry)} | SL ${f(a.sl)} | TP ${f(a.tp)}`});}
$("notify").onclick=async()=>{if("Notification"in window){const p=await Notification.requestPermission();$("notify").textContent=p==="granted"?"🔔 Notifikasi aktif":"🔕 Notifikasi ditolak";}};
$("theme").onclick=()=>document.body.classList.toggle("alt");
$("pair").onchange=load;$("tf").onchange=load;
$("calc").onclick=()=>{const bal=+$("bal").value,risk=+$("risk").value,entry=+$("ce").value,sl=+$("csl").value,tp=+$("ctp").value;const rn=bal*risk/100,dist=Math.abs(entry-sl),rr=dist?Math.abs(tp-entry)/dist:0;const lot=dist?rn/dist:0;$("calcOut").textContent=`Risk nominal: ${$("cur").value} ${rn.toLocaleString()} · R:R: 1:${rr.toFixed(2)} · Lot estimasi: ${lot.toFixed(4)} (sesuaikan contract size broker)`};
setInterval(()=>{count=count<=1?20:count-1;$("timer").textContent=count+"s"},1000);setInterval(load,20000);load();window.addEventListener("resize",()=>chart.resize($("tvchart").clientWidth,$("tvchart").clientHeight));
if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js");
